apiVersion: ray.io/v1
kind: RayService
metadata:
  annotations:
  name: whisper-streaming
  namespace: default
spec:
  deploymentUnhealthySecondThreshold: 300
  rayClusterConfig:
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
          - env:
            - name: RAY_GRAFANA_IFRAME_HOST
              value: "https://o11y.raycluster.lindarr.people.aws.dev"
            - name: RAY_GRAFANA_HOST
              value: http://prometheus-grafana.prometheus-system.svc:80
            - name: RAY_PROMETHEUS_HOST
              value: http://prometheus-kube-prometheus-prometheus.prometheus-system.svc:9090
            image: 464616699298.dkr.ecr.ap-northeast-1.amazonaws.com/ray-ml-whisper-streaming:latest
            # rayproject/ray-ml:2.9.2-py310
            name: ray-head
            ports:
            - containerPort: 6379
              name: gcs
              protocol: TCP
            - containerPort: 8265
              name: dashboard
              protocol: TCP
            - containerPort: 10001
              name: client
              protocol: TCP
            - containerPort: 8000
              name: serve
              protocol: TCP
            resources:
              limits:
                cpu: "2"
                memory: 8G
              requests:
                cpu: "2"
                memory: 8G
            securityContext:
              capabilities:
                add:
                - SYS_PTRACE
            volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
          volumes:
          - emptyDir: {}
            name: ray-logs
    rayVersion: 2.9.2
    workerGroupSpecs:
    - groupName: gpu-group
      maxReplicas: 20
      minReplicas: 1
      rayStartParams: {}
      replicas: 1
      template:
        spec:
          containers:
          - image: 464616699298.dkr.ecr.ap-northeast-1.amazonaws.com/ray-ml-whisper-streaming:latest
            name: ray-worker
            resources:
              limits:
                cpu: 4
                memory: 16G
                nvidia.com/gpu: 1
              requests:
                cpu: 3
                memory: 12G
                nvidia.com/gpu: 1
            env:
            - name: 'PYANNOTE_AUTH_TOKEN'
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: password
            # volumeMounts:
              # - name: model-storage
                # mountPath: /serve_app/model
          # volumes:
            # - name: model-storage
              # persistentVolumeClaim:
                # claimName: efs-claim-sd-model
          tolerations:
          - effect: NoSchedule
            key: ray.io/node-type
            operator: Equal
            value: worker
  serveConfigV2: |
    applications:
      - name: whisper-streaming
        import_path: src.voice_stream_ai_server:app
        # runtime_env:
        deployments:
        - name: TranscriptionServer
          max_concurrent_queries: 5
          autoscaling_config:
            target_num_ongoing_requests_per_replica: 5
            min_replicas: 1
            max_replicas: 20
            initial_replicas: 1
  serviceUnhealthySecondThreshold: 900

