apiVersion: ray.io/v1
kind: RayService
metadata:
  annotations:
  name: whisper-streaming
  namespace: default
spec:
  deploymentUnhealthySecondThreshold: 300
  rayClusterConfig:
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
          - env:
            - name: RAY_GRAFANA_IFRAME_HOST
              value: "https://o11y.raycluster.lindarr.people.aws.dev"
            - name: RAY_GRAFANA_HOST
              value: http://prometheus-grafana.prometheus-system.svc:80
            - name: RAY_PROMETHEUS_HOST
              value: http://prometheus-kube-prometheus-prometheus.prometheus-system.svc:9090
            image: rayproject/ray-ml:2.9.0-py310-cpu
            # image: 464616699298.dkr.ecr.ap-northeast-1.amazonaws.com/ray-ml-stable-diffusion:latest

            name: ray-head
            ports:
            - containerPort: 6379
              name: gcs
              protocol: TCP
            - containerPort: 8265
              name: dashboard
              protocol: TCP
            - containerPort: 10001
              name: client
              protocol: TCP
            - containerPort: 8000
              name: serve
              protocol: TCP
            resources:
              limits:
                cpu: "2"
                memory: 8G
              requests:
                cpu: "2"
                memory: 8G
            securityContext:
              capabilities:
                add:
                - SYS_PTRACE
            volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
          volumes:
          - emptyDir: {}
            name: ray-logs
    rayVersion: 2.9.0
    workerGroupSpecs:
    - groupName: gpu-group
      # serviceType: NodePort
      maxReplicas: 20
      minReplicas: 1
      rayStartParams: {}
      replicas: 1
      template:
        spec:
          containers:
          # - image: 464616699298.dkr.ecr.ap-northeast-1.amazonaws.com/ray-ml-stable-diffusion:latest
          - image: rayproject/ray-ml:2.9.0-py310
            name: ray-worker
            resources:
              limits:
                cpu: 4
                memory: 16G
                nvidia.com/gpu: 1
              requests:
                cpu: 3
                memory: 12G
                nvidia.com/gpu: 1
            env:
            - name: 'PYANNOTE_AUTH_TOKEN'
              value: '' # your HF TOKEN
            # volumeMounts:
              # - name: model-storage
                # mountPath: /serve_app/model
          # volumes:
            # - name: model-storage
              # persistentVolumeClaim:
                # claimName: efs-claim-sd-model
          tolerations:
          - effect: NoSchedule
            key: ray.io/node-type
            operator: Equal
            value: worker
  serveConfigV2: |
    applications:
      - name: whisper-streaming
        import_path: src.voice_stream_ai_server:app
        # import_path: stable_diffusion.stable_diffusion:entrypoint
        runtime_env:
        #  working_dir: "/serve_app/"
          working_dir: "https://github.com/lindarr915/VoiceStreamAI/archive/65be10ebee27e8f13b65e131d187c42646f68986.zip"
          pip: [
            "faster-whisper==0.10.0",
            "pyannote.audio==3.1.1",
            "transformers==4.37.2",
            "TorchAudio==2.2.0",
            "torchtext==0.17.0",
            "pyannote.core==5.0.0",
            "sentence-transformers==2.3.1",
            "asyncio==3.4.3",
            "torch==2.2.0",
            "lightning_fabric==2.2.0.post0",
            "lightning-bolts==0.7.0"
          ]
        deployments:
        - name: TranscriptionServer
          max_concurrent_queries: 5
          autoscaling_config:
            target_num_ongoing_requests_per_replica: 2
            min_replicas: 1
            max_replicas: 20
            initial_replicas: 1
  serviceUnhealthySecondThreshold: 900

